AWSTemplateFormatVersion: 2010-09-09
Description: Main project stack deployed by the CICD and containing specific nested stacks

Parameters:
  ProjectName:
    Type: String

Resources:
  StaticWebsiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
      TemplateURL: ./templates/static-website.yml
      TimeoutInMinutes: 15
      Tags:
        - Key: Project
          Value: !Ref ProjectName
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        WebsiteDomainName: !GetAtt StaticWebsiteStack.Outputs.WebsiteDomainName
      TemplateURL: ./templates/cognito.yml
      TimeoutInMinutes: 10
      Tags:
        - Key: Project
          Value: !Ref ProjectName
  GraphQLApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        CognitoUserPoolId: !GetAtt CognitoStack.Outputs.CognitoUserPoolId
        CognitoUserPoolClientId: !GetAtt CognitoStack.Outputs.CognitoUserPoolClientId
      TemplateURL: ./templates/graphqlapi.yml
      TimeoutInMinutes: 10
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  StaticWebBucket:
    Description: Name of the web bucket containing the website
    Value: !GetAtt StaticWebsiteStack.Outputs.StaticWebBucket
  WebsiteUrl:
    Description: URL of the website
    Value: !Sub https://${StaticWebsiteStack.Outputs.WebsiteDomainName}/
  CognitoUserPoolId:
    Description: The Cognito UserPool ID
    Value: !GetAtt CognitoStack.Outputs.CognitoUserPoolId
  CognitoUserPoolClientId:
    Description: The Cognito UserPool client ID
    Value: !GetAtt CognitoStack.Outputs.CognitoUserPoolClientId
  CognitoDomainName:
    Description: Domain of Cognito
    Value: !GetAtt CognitoStack.Outputs.CognitoDomainName
  GraphQLApiUrl:
    Description: GraphQL API URL
    Value: !GetAtt GraphQLApiStack.Outputs.ApiUrl
  GraphQLApiKey:
    Description: The Public API key of the API
    Value: !GetAtt GraphQLApiStack.Outputs.ApiKey
